name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx furo breathe
        sudo apt-get install doxygen graphviz

    - name: Build Doxygen Documentation
      run: doxygen Doxyfile

    - name: Build Sphinx Documentation
      run: sphinx-build -b html ./source ./build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        publish_branch: gh-pages
