name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx furo breathe
        sudo apt-get install doxygen graphviz

    - name: Build Doxygen Documentation
      run: doxygen Doxyfile

    - name: Build Sphinx Documentation
      run: sphinx-build -b html ./source ./docs

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add docs
        git commit -m "Update documentation"
        git push origin gh-pages --force
